# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEditFirst = QtWidgets.QLineEdit(Dialog)
        self.lineEditFirst.setGeometry(QtCore.QRect(200, 60, 113, 20))
        self.lineEditFirst.setObjectName("lineEditFirst")
        self.lineEditSecond = QtWidgets.QLineEdit(Dialog)
        self.lineEditSecond.setGeometry(QtCore.QRect(200, 110, 113, 20))
        self.lineEditSecond.setObjectName("lineEditSecond")
        self.labelFirst = QtWidgets.QLabel(Dialog)
        self.labelFirst.setGeometry(QtCore.QRect(70, 60, 111, 16))
        self.labelFirst.setObjectName("labelFirst")
        self.labelSecond = QtWidgets.QLabel(Dialog)
        self.labelSecond.setGeometry(QtCore.QRect(70, 110, 111, 16))
        self.labelSecond.setObjectName("labelSecond")
        self.labelResult = QtWidgets.QLabel(Dialog)
        self.labelResult.setGeometry(QtCore.QRect(50, 250, 321, 31))
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.pushButtonPlus = QtWidgets.QPushButton(Dialog)
        self.pushButtonPlus.setGeometry(QtCore.QRect(90, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonPlus.setFont(font)
        self.pushButtonPlus.setObjectName("pushButtonPlus")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButtonSubtract = QtWidgets.QPushButton(Dialog)
        self.pushButtonSubtract.setGeometry(QtCore.QRect(150, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonSubtract.setFont(font)
        self.pushButtonSubtract.setObjectName("pushButtonSubtract")
        self.pushButtonMultiply = QtWidgets.QPushButton(Dialog)
        self.pushButtonMultiply.setGeometry(QtCore.QRect(210, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonMultiply.setFont(font)
        self.pushButtonMultiply.setObjectName("pushButtonMultiply")
        self.pushButtonDivide = QtWidgets.QPushButton(Dialog)
        self.pushButtonDivide.setGeometry(QtCore.QRect(270, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonDivide.setFont(font)
        self.pushButtonDivide.setObjectName("pushButtonDivide")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelFirst.setText(_translate("Dialog", "First Number"))
        self.labelSecond.setText(_translate("Dialog", "Second Number"))
        self.pushButtonPlus.setText(_translate("Dialog", "+"))
        self.label_3.setText(_translate("Dialog", "CALCULATOR"))
        self.pushButtonSubtract.setText(_translate("Dialog", "-"))
        self.pushButtonMultiply.setText(_translate("Dialog", "x"))
        self.pushButtonDivide.setText(_translate("Dialog", "/"))
