# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoSliders.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(454, 356)
        self.horizontalScrollBarSugar = QtWidgets.QScrollBar(Dialog)
        self.horizontalScrollBarSugar.setGeometry(QtCore.QRect(190, 20, 160, 16))
        self.horizontalScrollBarSugar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBarSugar.setObjectName("horizontalScrollBarSugar")
        self.verticalScrollBarPulse = QtWidgets.QScrollBar(Dialog)
        self.verticalScrollBarPulse.setGeometry(QtCore.QRect(170, 120, 16, 160))
        self.verticalScrollBarPulse.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarPulse.setObjectName("verticalScrollBarPulse")
        self.horizontalSliderBlood = QtWidgets.QSlider(Dialog)
        self.horizontalSliderBlood.setGeometry(QtCore.QRect(200, 60, 160, 22))
        self.horizontalSliderBlood.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBlood.setObjectName("horizontalSliderBlood")
        self.verticalSliderCholesterol = QtWidgets.QSlider(Dialog)
        self.verticalSliderCholesterol.setGeometry(QtCore.QRect(350, 120, 22, 160))
        self.verticalSliderCholesterol.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderCholesterol.setObjectName("verticalSliderCholesterol")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(56, 20, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(56, 60, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(150, 100, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(330, 100, 61, 21))
        self.label_4.setObjectName("label_4")
        self.lineEditResult = QtWidgets.QLineEdit(Dialog)
        self.lineEditResult.setGeometry(QtCore.QRect(190, 310, 113, 20))
        self.lineEditResult.setObjectName("lineEditResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sugar Level"))
        self.label_2.setText(_translate("Dialog", "Blood Pressure"))
        self.label_3.setText(_translate("Dialog", "Pulse Rate"))
        self.label_4.setText(_translate("Dialog", "Cholesterol"))
